//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoDao2MiniGUI.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MoDao2MiniGUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 [KeyBoard]
        ///VK_0=&lt;11&gt;
        ///VK_1=&lt;2&gt;
        ///VK_2=&lt;3&gt;
        ///VK_3=&lt;4&gt;
        ///VK_4=&lt;5&gt;
        ///VK_5=&lt;6&gt;
        ///VK_6=&lt;7&gt;
        ///VK_7=&lt;8&gt;
        ///VK_8=&lt;9&gt;
        ///VK_9=&lt;10&gt;
        ///VK_A=&lt;30&gt;//a
        ///VK_B=&lt;48&gt;//b
        ///VK_C =&lt;46&gt;//c
        ///VK_D =&lt;32&gt;//d
        ///VK_E =&lt;18&gt;//e
        ///VK_F =&lt;33&gt;//f
        ///VK_G =&lt;34&gt;//g
        ///VK_H =&lt;35&gt;//h
        ///VK_I =&lt;23&gt;//i
        ///VK_J =&lt;36&gt;//j
        ///VK_K =&lt;37&gt;//k
        ///VK_L =&lt;38&gt;//l
        ///VK_M =&lt;50&gt;//m
        ///VK_N =&lt;49&gt;//n
        ///VK_O =&lt;24&gt;//o
        ///VK_P =&lt;25&gt;//p
        ///VK_Q =&lt;16&gt;//q
        ///VK_R =&lt;19&gt;//r
        ///VK_S =&lt;31&gt;//s
        ///VK_T =&lt;20&gt;//t
        ///VK_U =&lt;22&gt;//u
        ///VK_V =&lt;47&gt;//v
        ///VK_W =&lt;17&gt;//w
        ///VK_X =&lt;45&gt;//x
        ///VK_Y =&lt;21&gt;//y
        ///VK_Z =&lt;44&gt;//z
        ///VK_Dot=&lt;52 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string KEYMAP_CT {
            get {
                return ResourceManager.GetString("KEYMAP_CT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统 VK_System
        ///取消 VK_CANCEL
        ///紧急 VK_URGENT
        ///下班 VK_XIABAN
        ///下班B VK_XIABAN
        ///上班 VK_SHANGBAN
        ///上班A  VK_SHANGBAN
        ///X VK_CLOSE_YPD
        ///XI VK_CLOSE_YPD
        ///↓ VK_OPEN_YPD
        ///↓H  VK_OPEN_YPD
        ///欠款 VK_QIANKUAN
        ///备用 VK_BEIYONG
        ///上 VK_UP
        ///上V  VK_UP
        ///下U VK_DOWN
        ///下 VK_DOWN
        ///违章  VK_WEIZHANG
        ///违章C VK_WEIZHANG
        ///军车 VK_JUNCHE
        ///军警D VK_JUNCHE
        ///公务 VK_GONGWU
        ///公务E VK_GONGWU
        ///点 VK_Dot
        ///0 VK_0
        ///00 VK_00
        ///00J VK_00
        ///1 VK_1
        ///2 VK_2
        ///3 VK_3
        ///4 VK_4
        ///5 VK_5
        ///6 VK_6
        ///7 VK_7
        ///8 VK_8
        ///9 VK_9
        ///优惠 VK_YOUHUICARD
        ///优惠F VK_YOUHUICARD
        ///月票 VK_MOUNTHCARD
        ///月票G VK_MOU [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string KeyName {
            get {
                return ResourceManager.GetString("KeyName", resourceCulture);
            }
        }
    }
}
